import { motion } from 'motion/react';
import { PanelFrame, TapestryBand } from '../components/ui/ChronicleComponents';

export default function Terms() {
  return (
    <div className="flex flex-col min-h-screen bg-linen text-warp">
      {/* Banner */}
      <div className="py-16 bg-umber text-center text-linen shadow-lg relative z-10">
        <h1 className="font-engraved font-bold text-3xl tracking-widest uppercase">Terms of Trade</h1>
        <p className="font-prose text-sm italic text-gilt mt-2">The Roundtable Ventures Limited &bull; Statutes of International Commerce</p>
      </div>

      <div className="max-w-4xl mx-auto w-full px-6 py-16 flex-grow">
        <motion.div 
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="flex flex-col gap-12"
        >
          {/* Intro Seal */}
          <div className="text-center max-w-2xl mx-auto">
            <span className="font-blackletter text-4xl text-madder">T</span>
            <p className="font-prose text-lg text-warp/80 italic mt-2">
              "We trade only on binding specifications, verified weight, and secure credit. No container leaves the yard without the seal of the inspector and the endorsement of the bank."
            </p>
            <div className="h-[1px] w-24 bg-gilt/40 mx-auto mt-6" />
          </div>

          <PanelFrame className="p-8 md:p-12 bg-umber/60 border-gilt/15 shadow-sm">
            <div className="flex flex-col gap-10">
              
              {/* Sec 1 */}
              <div>
                <h2 className="font-gothic text-2xl text-madder border-b border-thread/20 pb-2 mb-4">I. Definition & Interpretations</h2>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85">
                  Herein, <strong>"The Desk"</strong> or <strong>"Seller"</strong> shall refer to <strong>The Roundtable Ventures Limited</strong>. <strong>"Buyer"</strong> refers to the entity contracting to purchase agricultural commodities. <strong>"Good"</strong> or <strong>"Cargo"</strong> refers to raw or processed commodities listed on the formal Contract (including Palm Oil, Sesame Seeds, Beans, Hibiscus, Soybeans, Cashew Nuts, River Catfish, and Ginger). <strong>"Surveyor"</strong> refers to international neutral auditing surveyors (SGS, Bureau Veritas, or Cotecna).
                </p>
              </div>

              {/* Sec 2 */}
              <div>
                <h2 className="font-gothic text-2xl text-madder border-b border-thread/20 pb-2 mb-4">II. Quotation Requests and Sealing of Price</h2>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85 mb-3">
                  All quotations generated by our web portal, email channels, or physical trade desks represent <strong>provisional estimates</strong> and do not constitute a final binding contract.
                </p>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85">
                  Due to the high seasonal volatility of African agricultural crops and maritime container rates, standard pricing remains valid for exactly <strong>seven (7) calendar days</strong> from the date of the formal quotation sheet. Prices must be officially locked or "sealed" via a mutual Sales Contract signed by both the Buyer's representative and our Desk.
                </p>
              </div>

              {/* Sec 3 */}
              <div>
                <h2 className="font-gothic text-2xl text-madder border-b border-thread/20 pb-2 mb-4">III. Standard Incoterms & Maritime Transfer</h2>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85 mb-3">
                  All trade deliveries are executed strictly in accordance with <strong>Incoterms 2020</strong> standards as agreed in the Contract. Standard terms offered by our Desk are:
                </p>
                <ul className="list-disc pl-6 space-y-2 font-prose text-[15px] text-warp/80">
                  <li><strong>FOB (Free On Board):</strong> Cargo risk transfer occurs as the goods clear the ship's rail at the named departure harbor (e.g., Port of Lagos, Port of Tema, Port of Mombasa).</li>
                  <li><strong>CIF (Cost, Insurance & Freight) & CFR (Cost & Freight):</strong> Seller covers shipping freight to named destination harbor. Risk passes on loading; Buyer covers destination custom fees & demurrages.</li>
                </ul>
              </div>

              {/* Sec 4 */}
              <div>
                <h2 className="font-gothic text-2xl text-madder border-b border-thread/20 pb-2 mb-4">IV. Trade Settlement & Letters of Credit</h2>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85 mb-3">
                  To ensure maximum sovereign transparency, all international trade contracts are settled strictly via one of the following instruments:
                </p>
                <ul className="list-disc pl-6 space-y-2 font-prose text-[15px] text-warp/80">
                  <li><strong>Irrevocable, Confirmed Letter of Credit (L/C) at Sight:</strong> Opened by a tier-1 global bank or fully confirmed by a prime correspondent bank, payable 100% against shipping documents (Bill of Lading, Certificate of Origin, Quality Certificate, Phytosanitary Certificate).</li>
                  <li><strong>T/T (Telegraphic Transfer):</strong> Standard 30% advance deposit for packaging and inland mobilization, with the remaining 70% paid upon submission of scanned shipping tallies and master bills of lading.</li>
                </ul>
              </div>

              {/* Sec 5 */}
              <div>
                <h2 className="font-gothic text-2xl text-madder border-b border-thread/20 pb-2 mb-4">V. Quality Inspection, Tolerances & Phytosanitary Checks</h2>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85 mb-3">
                  All shipments are inspected prior to loading at the departure harbor by an authorized third-party surveyor (e.g. SGS). This inspection provides the <strong>definitive determination</strong> of quality, weight, and grade.
                </p>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85">
                  Natural commodities carry organic tolerances (including humidity margins, dirt ad-mixtures, and size variances). The sales agreement shall detail accepted parameter ranges. Any deviation outside specifications verified by SGS on departure will trigger localized price adjustments or custom re-cleansing of the shipment.
                </p>
              </div>

              {/* Sec 6 */}
              <div>
                <h2 className="font-gothic text-2xl text-madder border-b border-thread/20 pb-2 mb-4">VI. Force Majeure & Crop Non-Performance</h2>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85 mb-3">
                  Neither party shall be held liable for failure or delay of loading due to acts of God, extreme atmospheric events, trade embargoes, state shipping prohibitions, maritime labor strikes, localized blockades, or sudden severe agricultural blights.
                </p>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85">
                  In instances of declared Force Majeure, the contracted loading window gets extended by a period proportional to the blockage, up to a maximum of 45 days. After this point, either party may rescind the unperformed cargo contract without penalty.
                </p>
              </div>

              {/* Sec 7 */}
              <div>
                <h2 className="font-gothic text-2xl text-madder border-b border-thread/20 pb-2 mb-4">VII. Demurrages & Port Detention</h2>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85">
                  If ship loading gets delayed by causes directly attributable to the buyer (such as failure to name sailing vessels on time or missing payment certifications), the buyer shall cover all demurrage costs and vessel penalties accumulated at the departure terminal.
                </p>
              </div>

              {/* Sec 8 */}
              <div>
                <h2 className="font-gothic text-2xl text-madder border-b border-thread/20 pb-2 mb-4">VIII. Governing Law & Arbitration Tribunal</h2>
                <p className="font-prose text-[15px] leading-relaxed text-warp/85">
                  These standard trade provisions and the contract issued there-under are governed and construed in accordance with English Law or local GAFTA (Grain and Feed Trade Association) or FOSFA (Federation of Oils, Seeds and Fats Associations) criteria. Any legal action or unresolved dispute shall be referred to the corresponding international trade arbitration panels.
                </p>
              </div>

            </div>
          </PanelFrame>

          <TapestryBand thin />

          <div className="text-center font-prose text-xs text-warp/60 italic">
            These Terms of Trade constitute the complete standing provisions of The Roundtable Ventures Limited as of June 14, 2026.
          </div>

        </motion.div>
      </div>
    </div>
  );
}
